version: '3.8'

services:
  toggl_time_logger:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./start_messages.txt:/app/start_messages.txt
      - ./end_messages.txt:/app/end_messages.txt
      - ./main.py:/app/main.py
    environment:
      - EMAIL=xxxx@gmail.com
      - PASSWORD=xxxx
      - WORKSPACE_ID=6104885
      # - PROJECT_ID=your_project_id
      - TZ=Asia/Bangkok
    command: ["python", "main.py"]
    restart: always